### ISSUE TITLE
dragonfly restart crash

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1305]
stacktrace below.
run using the following command:
```
/data/app/dragonfly-x86_64 --logtostderr --cache_mode=true --dbnum 16 --bind 0.0.0.0 --port 6379 --save_schedule *:30 --maxmemory=230g --keys_output_limit=12288 --dir /data/app/ --requirepass ... --masterauth ...  >> /data/app/dragonfly.log 2>&1 & 
```

from the log I see the load procedure has finished but some threads are still loading (LoadItemsBuffer). 
reported by @kissingtiger

his machine is 256GB, 128 cpu machine (not sure if number of threads is relevant).
Also, not clear to me why it's "key loaded: 0".

```
I20230529 14:10:12.530941 134156 proactor_pool.cc:73] Running 128 io threads
I20230529 14:10:12.811714 134156 server_family.cc:166] Data directory is "/data/app"
I20230529 14:10:12.814015 134156 server_family.cc:654] Loading /data/app/dump-2023-05-28T23:43:13-summary.dfs
I20230529 14:10:12.856622 134171 server_family.cc:752] Done loading RDB, keys loaded: 0
I20230529 14:10:12.856663 134171 server_family.cc:753] Loading finished after 41 ms
I20230529 14:10:12.882462 134180 listener_interface.cc:96] sock[386] AcceptServer - listening on port 6379
W20230529 14:10:12.906056 134183 dfly_main.cc:169] Remote version - HTTP GET error [version.dragonflydb.io:443/v1], error: 337047686
W20230529 14:10:12.906100 134183 dfly_main.cc:171] ssl error: tls_process_server_certificate/certificate verify failed

Thread 110 "Proactor108" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5133640 (LWP 134596)]
dfly::detail::Segment<dfly::CompactObj, dfly::ExpirePeriod, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::SegmentPolicy>::Bucket::FindByFp<dfly::CompactObj&, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::EqPred() const::{lambda(auto:1 const&, auto:2 const&)#1}&>(unsigned char, bool, dfly::CompactObj&, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::EqPred() const::{lambda(auto:1 const&, auto:2 const&)#1}&) const [clone .constprop.0] () at ../src/core/dash_internal.h:973
973 ../src/core/dash_internal.h: No such file or directory.
#0 dfly::detail::Segment<dfly::CompactObj, dfly::ExpirePeriod, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::SegmentPolicy>::Bucket::FindByFp<dfly::CompactObj&, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::EqPred() const::{lambda(auto:1 const&, auto:2 const&)#1}&>(unsigned char, bool, dfly::CompactObj&, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::EqPred() const::{lambda(auto:1 const&, auto:2 const&)#1}&) const [clone .constprop.0] () at ../src/core/dash_internal.h:973
#1 0x0000555555792756 in dfly::detail::Segment<dfly::CompactObj, dfly::ExpirePeriod, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::SegmentPolicy>::FindIt<dfly::CompactObj&, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::EqPred() const::{lambda(auto:1 const&, auto:2 const&)#1}>(dfly::CompactObj&, unsigned long, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::EqPred() const::{lambda(auto:1 const&, auto:2 const&)#1}&&) const () at ../src/core/dash_internal.h:1069
#2 0x0000555555615410 in dfly::detail::Segment<dfly::CompactObj, dfly::ExpirePeriod, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::SegmentPolicy>::Insert<dfly::CompactObj, dfly::ExpirePeriod, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::EqPred() const::{lambda(auto:1 const&, auto:2 const&)#1}>(dfly::CompactObj&&, dfly::ExpirePeriod&&, unsigned long, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::EqPred() const::{lambda(auto:1 const&, auto:2 const&)#1}&&) () at ../src/core/dash_internal.h:1048
#3 dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::InsertInternal<dfly::CompactObj, dfly::ExpirePeriod, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::DefaultEvictionPolicy>(dfly::CompactObj&&, dfly::ExpirePeriod&&, dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::DefaultEvictionPolicy&) [clone .constprop.0] () at ../src/core/dash.h:729
#4 0x000055555570a10d in dfly::DashTable<dfly::CompactObj, dfly::ExpirePeriod, dfly::detail::ExpireTablePolicy>::Insert<dfly::CompactObj, dfly::ExpirePeriod> () at ../src/core/dash.h:138
#5 dfly::DbSlice::AddOrUpdateInternal () at ../src/server/db_slice.cc:703
#6 0x000055555570a3a0 in dfly::DbSlice::AddOrUpdate () at ../src/server/db_slice.cc:715
#7 0x00005555558406ce in dfly::RdbLoader::LoadItemsBuffer () at ../src/server/rdb_load.cc:2168
#8 operator() () at ../src/server/rdb_load.cc:2141
#9 _M_invoke () at /usr/include/c++/9/bits/std_function.h:300
#10 0x000055555564e445 in std::function<void ()>::operator()() const () at /usr/include/c++/9/bits/std_function.h:688
#11 util::fb2::FiberQueue::Run () at ../helio/util/fibers/fiberqueue_threadpool.cc:45
#12 0x00005555556f8ab8 in operator() () at ../src/server/engine_shard_set.cc:204
#13 __invoke_impl<void, dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()> > () at /usr/include/c++/9/bits/invoke.h:60
#14 __invoke<dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()> > () at /usr/include/c++/9/bits/invoke.h:95
#15 __apply_impl<dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()>, std::tuple<> > () at /usr/include/c++/9/tuple:1684
#16 apply<dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()>, std::tuple<> > () at /usr/include/c++/9/tuple:1694
#17 run_ () at ../helio/util/fibers/detail/fiber_interface.h:218
#18 operator() () at ../helio/util/fibers/detail/fiber_interface.h:207
#19 __invoke_impl<boost::context::fiber, util::fb2::detail::WorkerFiberImpl<Fn, Arg>::WorkerFiberImpl(std::string_view, const boost::context::preallocated&, StackAlloc&&, Fn&&, Arg&& ...) [with StackAlloc = boost::context::basic_fixedsize_stack<boost::context::stack_traits>; Fn = dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()>; Arg = {}]::<lambda(util::fb2::detail::WorkerFiberImpl<dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()> >::FbCntx&&)>&, boost::context::fiber> () at /usr/include/c++/9/bits/invoke.h:60
#20 __invoke<util::fb2::detail::WorkerFiberImpl<Fn, Arg>::WorkerFiberImpl(std::string_view, const boost::context::preallocated&, StackAlloc&&, Fn&&, Arg&& ...) [with StackAlloc = boost::context::basic_fixedsize_stack<boost::context::stack_traits>; Fn = dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()>; Arg = {}]::<lambda(util::fb2::detail::WorkerFiberImpl<dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()> >::FbCntx&&)>&, boost::context::fiber> () at /usr/include/c++/9/bits/invoke.h:96
#21 invoke<util::fb2::detail::WorkerFiberImpl<Fn, Arg>::WorkerFiberImpl(std::string_view, const boost::context::preallocated&, StackAlloc&&, Fn&&, Arg&& ...) [with StackAlloc = boost::context::basic_fixedsize_stack<boost::context::stack_traits>; Fn = dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()>; Arg = {}]::<lambda(util::fb2::detail::WorkerFiberImpl<dfly::EngineShard::EngineShard(util::fb2::ProactorBase*, bool, mi_heap_t*)::<lambda()> >::FbCntx&&)>&, boost::context::fiber> () at /usr/include/c++/9/functional:82
```

**Comment by romange** [comment]
the user sent TERM signal to the process during the load. Seems that during shutdown sequence the rdb load fiber was still active (and it should not be).

**Comment by romange** [comment]
to reproduce the problem run:
```
service dragonfly stop
service dragonfly start

```

wrapper start script:
```
cat dragonfly-start.sh

#!/bin/bash
cd /data/app/
/data/app/dragonfly-x86_64 --logtostderr --cache_mode=true --dbnum 16 --bind 0.0.0.0 --port 6379 --save_schedule *:30 --maxmemory=230g --keys_output_limit=12288 --dir /data/app/   >> /data/app/dragonfly.log 2>&1 &

echo $! > /run/dragonfly.pid
```

service file:

```
cat /usr/lib/systemd/system/dragonfly.service 
[Unit]
Description=Dragonfly
After=network.target

[Service]
Type=forking
PIDFile=/run/dragonfly.pid
ExecStart=/data/app/dragonfly-start.sh
#PrivateTmp=true
KillMode=process
Restart=on-failure
RestartSec=30
RemainAfterExit=yes


[Install]
WantedBy=multi-user.target 

```
