### ISSUE TITLE
Incompatibility between DragonflyDB and redis/rueidis client

### ISSUE THREAD

**Issue by thisismz** [dragonflydb/dragonfly#2454]
**RESP3 support missing for rueidis DragonflyDB connection?**
# Error when connecting to DragonflyDB with rueidis client

When trying to connect to a DragonflyDB instance using the rueidis Redis client library in Go, I get the following panic:

`panic: Unknown subcommand or wrong number of arguments for 'TRACKING'. Try CLIENT HELP.: ClientOption.DisableCache must be true for redis not supporting client-side caching or not supporting RESP3 [recovered] panic: Unknown subcommand or wrong number of arguments for 'TRACKING'. Try CLIENT HELP.: ClientOption.DisableCache must be true for redis not supporting client-side caching or not supporting RESP3`

This happens with the following code:

```go
package main

import (
	"context"
	"fmt"

	"github.com/redis/rueidis"
)

func main() {
	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6379"}})
	if err != nil {
		panic(err)
	}
	defer client.Close()

	ctx := context.Background()
	// SET key val NX
	err = client.Do(ctx, client.B().Set().Key("key").Value("val").Nx().Build()).Error()
	if err != nil {
		panic(err)
	}
	res, err := client.Do(ctx, client.B().Get().Key("key").Build()).ToString()
	if err != nil {
		panic(err)
	}
	fmt.Println(res)
}

```
It seems there may be an incompatibility between DragonflyDB and the rueidis client assumptions. Specifically the error suggests rueidis expects disabled client caching or RESP3 support.

I checked the DragonflyDB docs but didn't see mention of RESP3 support or client caching handling.

Could this be added to enable better compatibility with Redis clients like rueidis? Or is there another recommended approach for connecting to DragonflyDB from Go code?

Let me know if any other details would be helpful in resolving this. Thanks!

**Feel free to modify or improve this as needed. Hopefully it clearly explains the issue you are seeing. Let me know if you have any other questions!**

**Comment by kostasrim** [comment]
Hi @thisismz, this should be a bug (we support both RESP3 and client side tracking). 

Let me get back to you on this one

**Comment by thisismz** [comment]
Yes, it seems that you are correct; the error appears to be different between Linux and Windows. I executed this on my MacBook and received the same error as you. let me the opportunity to double-check.

However, it seems that by adding the following parameter, it appears that the issue has been resolved:
```plaintext
DisableCache: true
```

``` GO
client, err := rueidis.NewClient(
	rueidis.ClientOption{
	InitAddress: []string{"127.0.0.1:6379"},
	DisableCache: true,
})
```
But when we set a key twice, we receive the following error:
```plaintext
panic: redis nil message
goroutine 1 [running]:
main.main()
        /Users/mozaffari/Documents/tst/dragonfly/main.go:22 +0x590
```
It seems like we might not have overwriting capabilities.

> Hi @thisismz , I run your example with go `1.21.6`. First, I am not quite sure how you are getting this output:
> 
> > 
> 
> panic: Unknown subcommand or wrong number of arguments for 'TRACKING'. Try CLIENT HELP.: ClientOption.DisableCache must be true for redis not supporting client-side caching or not supporting RESP3 [recovered] panic: Unknown subcommand or wrong number of arguments for 'TRACKING'. Try CLIENT HELP.: ClientOption.DisableCache must be true for redis not supporting client-side caching or not supporting RESP3
> 
> When I run it, I just get: `panic: syntax error`.
> 
> How I reproduced: `go mod init test && go get github.com/redis/rueidis && go run .` . The good thing is at least I managed to reproduce and figure out what the issue is. We recently added support for the `CLIENT TRACKING` subcommand in #2139 However, it appears that we only added partial support. The only tthing we accept is `CLIENT TRACKING ON/OFF`. However, `rueidis` sends `CLIENT TRACKING ON OPTIN` and dragonfly fails to parse the `OPTIN` arguments and returns with a `syntax error`.
> 
> Therefore to resolve this we need to parse the `OPTIN` argument + test with `ruedis`.
> 
> @romange what's the priority of this? Also, I noticed that we need to update the docs https://www.dragonflydb.io/docs/command-reference/compatibility to include `CLIENT TRACKING` I am mentioning it here so we don't forget

**Comment by thisismz** [comment]
Hello @kostasrim 

I checked again on Windows and got the same error that was reported. 

> panic: Unknown subcommand or wrong number of arguments for 'TRACKING'. Try CLIENT HELP.: ClientOption.DisableCache must be true for redis not supporting client-side caching or not supporting RESP3 [recovered] panic: Unknown subcommand or wrong number of arguments for 'TRACKING'. Try CLIENT HELP.: ClientOption.DisableCache must be true for redis not supporting client-side caching or not supporting RESP3

I'm using docker version 4.27.1 and 
dragonfly v1.13.0-f39eac5bcaf7c8ffe5c433a0e8e15747391199d9
build time: 2023-12-04 15:59:48
The only way it works for me is when DisableCache: true,

**Comment by kostasrim** [comment]
Hi @thisismz from a quick look the `flag` `DisableCache` seems to not use the `CLIENT TRACKING` command at all and that's why it works. Moreover, the reason you are getting `nil` message is because:

```
err = client.Do(ctx, client.B().Set().Key("key").Value("val").Nx().Build()).Error()
```

You call `Nx()` which only sets the key if it does not already exist. Therefore if you use the same code above twice, the second time will get you a `nil`. You can remove `Nx` and the example will work fine. 

> It seems like we might not have overwriting capabilities
You used `Nx()`

**Comment by rueian** [comment]
Hi all,

rueidis can send `CLIENT TRACKING ON` without `OPTIN` by doing this:

```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/redis/rueidis"
)

func main() {
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress:           []string{"127.0.0.1:6379"},
		ClientTrackingOptions: []string{},
	})
	if err != nil {
		panic(err)
	}
	defer client.Close()
	fmt.Println(client.DoCache(context.Background(), client.B().Get().Key("mykey").Cache(), time.Second).Error())
}

```

However, I found dragonfly would crash on the above `client.DoCache(...)` call like this:

```sh
I20240313 12:17:42.688308     9 listener_interface.cc:101] sock[7] AcceptServer - listening on port 6379
*** SIGSEGV received at time=1710332266 on cpu 0 ***
PC: @     0xaaaae1226770  (unknown)  dfly::Transaction::Refurbish()
    @     0xaaaae187cc7c        480  absl::lts_20230802::AbslFailureSignalHandler()
    @     0xffffacb3b7a0       4960  (unknown)
    @     0xaaaae12ce164        400  facade::Connection::DispatchOperations::operator()()
E20240313 12:17:46.477110     9 server_family.cc:1532] Subcommand CACHING not supported
    @     0xaaaae12d5164         32  facade::Connection::DispatchFiber()
    @     0xaaaae12d576c        384  boost::context::detail::fiber_entry<>()
```

I used the dragonfly docker image df-v1.15.1-d6703460242ab8aa415a93f32677c5f23b5e6ec8.

**Comment by kostasrim** [comment]
Hi @rueian, I think we do not support `CACHING` subcommand and I think the issue comes from `client.B().Get().Key("mykey").Cache()`, specifically the `Cache` part

**Comment by rueian** [comment]
Hi @kostasrim, Thank you for the prompt reply!

I understand that Dragonfly doesn't support the `CACHING` subcommand at this moment. However, I think a reasonable reaction to that should be returning an error like `-ERR Unknown subcommand or wrong number of arguments for 'CACHING'. Try CLIENT HELP.` instead of crashing.

**Comment by kostasrim** [comment]
Hi @rueian, turns out there was bigger issue on our side. I fixed it and you should be now getting a proper error message

**Comment by rueian** [comment]
Wow, thanks! That's amazing. I can't believe you fix this so fast.

**Comment by joeky888** [comment]
I think this issue should open until CLIENT TRACKING is implemented.

**Comment by romange** [comment]
@joeky888  it's gonna be fixed in 1.20.0

**Comment by joeky888** [comment]
@romange I can confirm it is working on my macbook! Thanks for informing me.

**Comment by kostasrim** [comment]
@joeky888 :100: :man_dancing:

**Comment by alessio-locatelli** [comment]
I searched the code, issues and discussions, but found no roadmaps. This is the most related issue I was able to find.  Is there any open issue or a webpage to track the progress about [Client-side caching](https://redis.io/docs/latest/develop/clients/client-side-caching/) support?

MRE (tested on DragonflyDB v1.26.1):

```py
import redis
from redis.cache import CacheConfig
r = redis.Redis(host='localhost', port=6379, password="redis_password", protocol=3, cache_config=CacheConfig())
r.ping()
```

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/commands/core.py", line 1212, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/connection.py", line 791, in connect
    raise ConnectionError(
redis.exceptions.ConnectionError: To maximize compatibility with all Redis products, client-side caching is supported by Redis 7.4 or later
>>> r.ping()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/commands/core.py", line 1212, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/redis/connection.py", line 791, in connect
    raise ConnectionError(
redis.exceptions.ConnectionError: To maximize compatibility with all Redis products, client-side caching is supported by Redis 7.4 or later
```

**Comment by kostasrim** [comment]
Hi @alessio-locatelli we do support client side caching. I will take a look and ping

**Comment by kostasrim** [comment]
Hi @alessio-locatelli, the library polls for `INFO command` field `redis_version` which we report as `7.2.0`. The library fails because of that. I will patch this in a few minutes and it should be included on the next release. Will update soon.

**Comment by kostasrim** [comment]
#4473

**Comment by kostasrim** [comment]
Fixed in https://github.com/dragonflydb/dragonfly/pull/4474

**Comment by romange** [comment]
Seems that Redis libraries are starting to require "redis_versions" that are post-fork. That's unfortunate and I do not want us to be dragged into this. version 7.4 is the last one we change @kostasrim - after that - we will only follow valkey.

**Comment by romange** [comment]
@alessio-locatelli  please try `valkey-py` instead of `redis-py`
