### ISSUE TITLE
Netbox Worker and Dragonfly

### ISSUE THREAD

**Issue by drag0n141** [dragonflydb/dragonfly#2784]
**Describe the bug**
I want to use Netbox with Dragonfly, but the worker pod does not start and gives this error when i am using dragonfly. The server pod does work and i can access netbox without any problem.

```
Defaulted container "netbox-worker" out of: netbox-worker, k8tz (init)
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
No queues have been specified. This process will service the following queues by default: high, default, low
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/core/management/commands/rqworker.py", line 28, in handle
    super().handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django_rq/management/commands/rqworker.py", line 90, in handle
    w = get_worker(*args, **worker_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django_rq/workers.py", line 50, in get_worker
    return worker_class(
           ^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/worker.py", line 211, in __init__
    client_adresses = [client['addr'] for client in connection.client_list() if client['name'] == self.name]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/worker.py", line 211, in <listcomp>
    client_adresses = [client['addr'] for client in connection.client_list() if client['name'] == self.name]
                                                                                ~~~~~~^^^^^^^^
KeyError: 'name'
```

**Environment (please complete the following information):**
 - OS: Debian 12
 - Kernel: 6.1
 - Containerized: Kubernetes
 - Dragonfly Version: 1.15.1

**Comment by romange** [comment]
I am sorry but we won't be able to help you with technical problems that outside of Dragonfly direct responsibility.

**Comment by drag0n141** [comment]
This is a problem with dragonfly, with normal redis both pods start without any problem. There is something with dragonfly.

**Comment by ashotland** [comment]
Hi @drag0n141 - I am not familiar with Netbox, perhaps you can share more details about what should be population that 'name' key from the stack trace you shared ?

Can you share a the configuration that work for you with redis but doesn't with dragonfly?

**Comment by drag0n141** [comment]
That's not that easy. I set only the redis server url in the helmchart. And that's the whole output of the pod.

**Comment by drag0n141** [comment]
I check later the source code if I can see something about that.
