### ISSUE TITLE
Dragonfly with celery and flower

### ISSUE THREAD

**Issue by Joseph94m** [dragonflydb/dragonfly#68]
Hey,

I am trying to replace redis with dragonfly in a django project. Celery and Flower are complaining that dragonfly does not have the PSUBSCRIBE command: "Unknown command 'PSUBSCRIBE'". i can see that you guys already have this in your crosshairs:

![Screenshot 2022-05-31 at 18 49 15](https://user-images.githubusercontent.com/40126230/171229631-63fd5641-0bc7-44d6-87aa-52fb114f0d4e.png)

Any idea when we can expect it to be available for testing?
Keep up the good work

**Comment by romange** [comment]
I will try to implement it in the next 2 weeks. Hopefully, it will be there in v0.2

**Comment by rodrigbap** [comment]
Muito bem.

**Comment by romange** [comment]
@Joseph94m   I am almost ready to release the alpha version that supports PSUBSCRIBE/PUNSUBSCRIBE.
will you be able to take it for a test run and see if there are things that missing?

**Comment by romange** [comment]
For the reference https://github.com/dragonflydb/dragonfly/commit/ec9754150f2df8e012f479eaf0682a0764abf8ce has been submitted to main.

**Comment by Joseph94m** [comment]
@romange Hello, yes I can take it for a test run! Do i need to clone the project to build the image or do you have an image already pushed on some registry?

**Comment by romange** [comment]
@Joseph94m  - no, no - I will build something for you.
do you mind if it will be a binary and not a docker image?

**Comment by Joseph94m** [comment]
I am currently using docker-compose (so yes, docker images) to start all of my project including redis (dragonfly). I guess i could instead run it on my mac (intel i7) if it is compiled for that purpose.

**Comment by Joseph94m** [comment]
Thanks, I am no longer seeing the PSUBSCRIBE errors at least. Now i'm seeing the following on my docker-compose trace:

```
initialisation logs....
redis_1     | I20220607 07:47:25.927485     1 server_family.cc:190] Data directory is "/data"
redis_1     | I20220607 07:47:25.927757     1 server_family.cc:224] Loading /data/dump.rdb
redis_1     | I20220607 07:47:25.937772    11 listener_interface.cc:79] sock[21] AcceptServer - listening on port 6379
redis_1     | I20220607 07:47:25.938098    14 rdb_load.cc:551] Loading RDB produced by version 6.2.7
redis_1     | I20220607 07:47:25.938158    14 rdb_load.cc:556] RDB age 7 days
redis_1     | I20220607 07:47:25.938206    14 rdb_load.cc:559] RDB memory usage when created 794.8KiB
redis_1     | I20220607 07:47:25.950022    14 rdb_load.cc:370] Done loading RDB, keys loaded: 2
redis_1     | I20220607 07:47:25.950125    14 rdb_load.cc:371] Loading finished after 12 ms
flower_1    | [I 220607 07:47:26 command:152] Visit me at http://localhost:5555
flower_1    | [I 220607 07:47:26 command:159] Broker: redis://redis:6379/1
flower_1    | [I 220607 07:47:26 command:160] Registered tasks: 
flower_1    |     ['celery.accumulate',
flower_1    |      'celery.backend_cleanup',
flower_1    |      'celery.chain',
flower_1    |      'celery.chord',
flower_1    |      'celery.chord_unlock',
flower_1    |      'celery.chunks',
flower_1    |      'celery.group',
flower_1    |      'celery.map',
flower_1    |      'celery.starmap',
flower_1    |      'core.tasks.start_analysis']
flower_1    | [I 220607 07:47:26 mixins:225] Connected to redis://redis:6379/1
flower_1    | [W 220607 07:47:27 inspector:42] Inspect method active failed
redis_1     | *** SIGILL received at time=1654588045 on cpu 1 ***
redis_1     | PC: @     0x55b68c1eca97  (unknown)  luaH_newkey
redis_1     |     @ ... and at least 1 more frames
celery_1    | [2022-06-07 07:47:25,326: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Connection closed by server..
celery_1    | Trying to reconnect...
celery_1    | 
celery_1    | [2022-06-07 07:47:25,331: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Error 111 connecting to redis:6379. Connection refused..
celery_1    | Trying again in 2.00 seconds... (1/100)
celery_1    | 
web_1       | Starting server
flower_1    | [I 220607 07:47:25 __init__:14] Pandas backend loaded 1.4.2
flower_1    | [I 220607 07:47:25 __init__:25] Numpy backend loaded 1.22.3
flower_1    | [I 220607 07:47:25 __init__:37] Pyspark backend NOT loaded
flower_1    | [I 220607 07:47:25 __init__:43] Python backend loaded
redis_1     | I20220607 07:47:25.927485     1 server_family.cc:190] Data directory is "/data"
redis_1     | I20220607 07:47:25.927757     1 server_family.cc:224] Loading /data/dump.rdb
redis_1     | I20220607 07:47:25.937772    11 listener_interface.cc:79] sock[21] AcceptServer - listening on port 6379
redis_1     | I20220607 07:47:25.938098    14 rdb_load.cc:551] Loading RDB produced by version 6.2.7
redis_1     | I20220607 07:47:25.938158    14 rdb_load.cc:556] RDB age 7 days
redis_1     | I20220607 07:47:25.938206    14 rdb_load.cc:559] RDB memory usage when created 794.8KiB
redis_1     | I20220607 07:47:25.950022    14 rdb_load.cc:370] Done loading RDB, keys loaded: 2
redis_1     | I20220607 07:47:25.950125    14 rdb_load.cc:371] Loading finished after 12 ms
flower_1    | [I 220607 07:47:26 command:152] Visit me at http://localhost:5555
flower_1    | [I 220607 07:47:26 command:159] Broker: redis://redis:6379/1
flower_1    | [I 220607 07:47:26 command:160] Registered tasks: 
flower_1    |     ['celery.accumulate',
flower_1    |      'celery.backend_cleanup',
flower_1    |      'celery.chain',
flower_1    |      'celery.chord',
flower_1    |      'celery.chord_unlock',
flower_1    |      'celery.chunks',
flower_1    |      'celery.group',
flower_1    |      'celery.map',
flower_1    |      'celery.starmap',
flower_1    |      'core.tasks.start_analysis']
flower_1    | [I 220607 07:47:26 mixins:225] Connected to redis://redis:6379/1
flower_1    | [W 220607 07:47:27 inspector:42] Inspect method active failed
redis_1     | *** SIGILL received at time=1654588047 on cpu 5 ***
redis_1     | PC: @     0x5555b054ba97  (unknown)  luaH_newkey
redis_1     |     @ ... and at least 1 more frames
flower_1    | [W 220607 07:47:27 inspector:42] Inspect method revoked failed
flower_1    | [E 220607 07:47:27 base_events:1753] Future exception was never retrieved
flower_1    |     future: <Future finished exception=ConnectionError("Error while reading from redis:6379 : (104, 'Connection reset by peer')")>
flower_1    |     Traceback (most recent call last):
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 821, in read_response
flower_1    |         response = self._parser.read_response(disable_decoding=disable_decoding)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 320, in read_response
flower_1    |         raw = self._buffer.readline()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 251, in readline
flower_1    |         self._read_from_socket()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 194, in _read_from_socket
flower_1    |         data = self._sock.recv(socket_read_size)
flower_1    |     ConnectionResetError: [Errno 104] Connection reset by peer
flower_1    |     
flower_1    |     During handling of the above exception, another exception occurred:
flower_1    |     
flower_1    |     Traceback (most recent call last):
flower_1    |       File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
flower_1    |         result = self.fn(*self.args, **self.kwargs)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/flower/inspector.py", line 38, in _inspect
flower_1    |         result = getattr(inspect, method)()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/celery/app/control.py", line 271, in registered
flower_1    |         return self._request('registered', taskinfoitems=taskinfoitems)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/celery/app/control.py", line 106, in _request
flower_1    |         return self._prepare(self.app.control.broadcast(
flower_1    |       File "/usr/local/lib/python3.9/site-packages/celery/app/control.py", line 741, in broadcast
flower_1    |         return self.mailbox(conn)._broadcast(
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/pidbox.py", line 344, in _broadcast
flower_1    |         return self._collect(reply_ticket, limit=limit,
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/pidbox.py", line 391, in _collect
flower_1    |         chan.after_reply_message_received(queue.name)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 537, in after_reply_message_received
flower_1    |         self.queue_delete(queue)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 533, in queue_delete
flower_1    |         self._delete(queue, exchange, *meta, **kwargs)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 1041, in _delete
flower_1    |         client.srem(self.keyprefix_queue % (exchange,),
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 3235, in srem
flower_1    |         return self.execute_command("SREM", name, *values)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1218, in execute_command
flower_1    |         return conn.retry.call_with_retry(
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 48, in call_with_retry
flower_1    |         fail(error)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1222, in <lambda>
flower_1    |         lambda error: self._disconnect_raise(conn, error),
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1208, in _disconnect_raise
flower_1    |         raise error
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 45, in call_with_retry
flower_1    |         return do()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1219, in <lambda>
flower_1    |         lambda: self._send_command_parse_response(
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1195, in _send_command_parse_response
flower_1    |         return self.parse_response(conn, command_name, **options)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1234, in parse_response
flower_1    |         response = connection.read_response()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 827, in read_response
flower_1    |         raise ConnectionError(f"Error while reading from {hosterr}" f" : {e.args}")
flower_1    |     redis.exceptions.ConnectionError: Error while reading from redis:6379 : (104, 'Connection reset by peer')
flower_1    | [E 220607 07:47:27 base_events:1753] Future exception was never retrieved
flower_1    |     future: <Future finished exception=ConnectionError('Connection closed by server.')>
flower_1    |     Traceback (most recent call last):
flower_1    |       File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
flower_1    |         result = self.fn(*self.args, **self.kwargs)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/flower/inspector.py", line 38, in _inspect
flower_1    |         result = getattr(inspect, method)()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/celery/app/control.py", line 177, in reserved
flower_1    |         return self._request('reserved')
flower_1    |       File "/usr/local/lib/python3.9/site-packages/celery/app/control.py", line 106, in _request
flower_1    |         return self._prepare(self.app.control.broadcast(
flower_1    |       File "/usr/local/lib/python3.9/site-packages/celery/app/control.py", line 741, in broadcast
flower_1    |         return self.mailbox(conn)._broadcast(
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/pidbox.py", line 344, in _broadcast
flower_1    |         return self._collect(reply_ticket, limit=limit,
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/pidbox.py", line 391, in _collect
flower_1    |         chan.after_reply_message_received(queue.name)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 537, in after_reply_message_received
flower_1    |         self.queue_delete(queue)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 533, in queue_delete
flower_1    |         self._delete(queue, exchange, *meta, **kwargs)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 1048, in _delete
flower_1    |         pipe.execute()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 2058, in execute
flower_1    |         return conn.retry.call_with_retry(
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 48, in call_with_retry
flower_1    |         fail(error)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 2060, in <lambda>
flower_1    |         lambda error: self._disconnect_raise_reset(conn, error),
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 45, in call_with_retry
flower_1    |         return do()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 2059, in <lambda>
flower_1    |         lambda: execute(conn, stack, raise_on_error),
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1913, in _execute_transaction
flower_1    |         self.parse_response(connection, "_")
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1998, in parse_response
flower_1    |         result = Redis.parse_response(self, connection, command_name, **options)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1234, in parse_response
flower_1    |         response = connection.read_response()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 821, in read_response
flower_1    |         response = self._parser.read_response(disable_decoding=disable_decoding)
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 320, in read_response
flower_1    |         raw = self._buffer.readline()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 251, in readline
flower_1    |         self._read_from_socket()
flower_1    |       File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 197, in _read_from_socket
flower_1    |         raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
flower_1    |     redis.exceptions.ConnectionError: Connection closed by server.
```
It loops like that for a while and then everything restarts
```
redis_1     | I20220607 07:47:27.893879     1 proactor_pool.cc:66] Running 6 io threads
redis_1     | I20220607 07:47:27.902966     1 server_family.cc:190] Data directory is "/data"
redis_1     | I20220607 07:47:27.903060     1 server_family.cc:224] Loading /data/dump.rdb
redis_1     | I20220607 07:47:27.910939    12 listener_interface.cc:79] sock[22] AcceptServer - listening on port 6379
redis_1     | I20220607 07:47:27.911105    15 rdb_load.cc:551] Loading RDB produced by version 6.2.7
redis_1     | I20220607 07:47:27.911149    15 rdb_load.cc:556] RDB age 7 days
redis_1     | I20220607 07:47:27.911206    15 rdb_load.cc:559] RDB memory usage when created 794.8KiB
redis_1     | I20220607 07:47:27.917959    15 rdb_load.cc:370] Done loading RDB, keys loaded: 2
redis_1     | I20220607 07:47:27.918016    15 rdb_load.cc:371] Loading finished after 7 ms
flower_1    | [I 220607 07:47:28 mixins:225] Connected to redis://redis:6379/1
redis_1     | *** SIGILL received at time=1654588048 on cpu 5 ***
redis_1     | PC: @     0x55f1a1dfda97  (unknown)  luaH_newkey
redis_1     |     @ ... and at least 1 more frames
flower_1    | [E 220607 07:47:28 events:184] Failed to capture events: 'Connection closed by server.', trying again in 1 seconds.
celery_1    | [2022-06-07 07:47:28,386: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Connection closed by server..
celery_1    | Trying to reconnect...
celery_1    | 
celery_1    | [2022-06-07 07:47:28,393: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Error 111 connecting to redis:6379. Connection refused..
celery_1    | Trying again in 2.00 seconds... (1/100)
celery_1    | 
redis_1 exited with code 132
redis_1     | I20220607 07:47:29.261397     1 server_family.cc:190] Data directory is "/data"
redis_1     | I20220607 07:47:29.261520     1 server_family.cc:224] Loading /data/dump.rdb
redis_1     | I20220607 07:47:29.262727    11 listener_interface.cc:79] sock[21] AcceptServer - listening on port 6379
redis_1     | I20220607 07:47:29.263067    14 rdb_load.cc:551] Loading RDB produced by version 6.2.7
redis_1     | I20220607 07:47:29.263124    14 rdb_load.cc:556] RDB age 7 days
redis_1     | I20220607 07:47:29.263159    14 rdb_load.cc:559] RDB memory usage when created 794.8KiB
redis_1     | I20220607 07:47:29.263943    14 rdb_load.cc:370] Done loading RDB, keys loaded: 2
redis_1     | I20220607 07:47:29.263995    14 rdb_load.cc:371] Loading finished after 1 ms
flower_1    | [I 220607 07:47:29 mixins:225] Connected to redis://redis:6379/1
redis_1     | *** SIGILL received at time=1654588050 on cpu 5 ***
redis_1     | PC: @     0x555e88c72a97  (unknown)  luaH_newkey
redis_1     |     @ ... and at least 1 more frames
celery_1    | [2022-06-07 07:47:30,410: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Connection closed by server..
celery_1    | Trying to reconnect...
celery_1    | 
flower_1    | [E 220607 07:47:30 events:184] Failed to capture events: 'Connection closed by server.', trying again in 1 seconds.
celery_1    | [2022-06-07 07:47:30,417: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Error 111 connecting to redis:6379. Connection refused..
celery_1    | Trying again in 2.00 seconds... (1/100)
celery_1    | 
```

Here are my configurations:

I think it's important to note that I did not change anything in the configurations of my celery broker/backend. My project behaves as if it is still trying to connect to redis/1 (for brokerage and backend) and 2 for caching (but i don't currently use caching so it shouldn't be a concern for now). Hmnnn... maybe i do need to change something in my conf ?

![image](https://user-images.githubusercontent.com/40126230/172328228-155c0d5d-b2f7-4ecc-9d8a-f9a4c337e4c8.png)

**Comment by romange** [comment]
@Joseph94m  it's super. Looks like you found a bug. No, you should not change anything. 

What I need is a way to reproduce it locally on my machine.
1. Can you send me your docker-compose.yml ?
2. Can you publish somehow your project so I could access it from docker-compose?

**Comment by romange** [comment]
Thanks! From the little I saw in those traces it's somehow related to Lua. But maybe I am mistaken.

**Comment by Joseph94m** [comment]
@romange here's a[ dummy project](https://github.com/Joseph94m/dummy-django) with one api entry point (get request):
http://localhost:8000/tester/hi/

Essentially it performs a get request on https://httpbin.org/delay/5, caches the result using `redis/2` and returns the data. It also creates a celery task that uses `redis/1` that prints some stuff on the command line.

To start the entire infra just run `docker-compose up --build` (i hope that works without you having to create any virtual python env, etc...)

If you want to replace redis by dragonflydb, you should uncomment `# image: docker.dragonflydb.io/dragonflydb/dragonfly:alpha` and the `ulimits` section and also comment image: `redis:6.2-alpine`

If you don't want to deal with caching and brokerage at the same time, let me know and i'll remove caching or you can do it yourself in tester.views.py (don't forget to `docker restart <celery_id>` after you do that otherwise it won't pickup the changes) if you are familiar with django projects.

The code is structured in such a way that any changes will cause the server to restart and reload newest changes (except for celery tasks).

**Comment by romange** [comment]
Do you know if containers withing docker-compose can access the external network ? 
i.e. if I run dragonfly externally on localhost, will I be able to replace `redis://redis:6379/1` with `redis://localhost:6379/1`

**Comment by TamCore** [comment]
You'll have to consider the network access from the POV of the container. If you want to access the dragonfly instance on your machine, you would either a) have to find your host's IP within Docker's overlay network, or b) connect against the IP that's directly assigned to your machine (like your LAN address). For ease of use I suggest the latter :)

**Comment by romange** [comment]
Got ya!

**Comment by romange** [comment]
@Joseph94m  I do not succeed to reproduce the problem. Does it happen on the first trigger of HTTP handler ? immediately on startup?

**Comment by romange** [comment]
@Joseph94m  I released v0.2.0.  Can you please check `docker.dragonflydb.io/dragonflydb/dragonfly:latest` and confirm it works for you?

**Comment by Joseph94m** [comment]
`docker.dragonflydb.io/dragonflydb/dragonfly:latest` doesn't work
`docker.dragonflydb.io/dragonflydb/dragonfly:v0.2.0` works for both the dummy project and the main one

Thanks!

**Comment by romange** [comment]
closing, feel free to reopen
